server:
  port: 8081

spring:
  application:
    name:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/SpringBootCloak
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      resource-id: SpringBoot-Keycloak-client
      principal-attribute: preferred_username

logging:
  level:
    org.springframework.security: DEBUG

